version: '3.8'
services:
  hello:
    image: navekom/webpage:hello
    volumes:
        - ./hello/html:/usr/share/nginx/html
        - ./hello/default.conf:/etc/nginx/conf.d/default.conf
    container_name: hello
    ports:
      - 9988:9988
  singlish:
    image: navekom/webpage:singlish
    volumes:
        - ./singlish/html:/usr/share/nginx/html
        - ./singlish/default.conf:/etc/nginx/conf.d/default.conf
    container_name: singlish
    ports:
      - 700:700
  reverse_proxy:
    image: navekom/reverse_proxy
    volumes:
      - ./reverse_proxy/default.conf:/etc/nginx/conf.d/default.conf
    container_name: reverse_proxy
    ports:
      - 80:80